branches:
  - master
extends:
  - semantic-release-preconfigured-conventional-commits
plugins:
  - "@@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - "@semantic-release/git"
