name: 'Compile and publish all LaTeX'
description: 'Checkout, compile LaTeX, compute a version, and deploy on GitHub in one shot.'
inputs:
  token:  # github token
    description: 'Github token for deployment.'
    required: true
  diff-enable:
    description: 'Github token for deployment. Skips deployment otherwise.'
    required: false
    default: false
  diff-files:
    description: Latex files (globs) to diff, if diff enabled
    required: false
    default: |
      **/*.tex
  diff-lightweight-tags:
    description: Whether non-annotated tags should be considered
    required: false
    default: false
  diff-tag-regex:
    description: Newline-separated list of tags to create differential documents with. Ruby Regex syntax supported.
    required: false
    default: |
      .*
  publish-enable:
    description: 'Whether the results should be deployed on GitHub. Defaults to true.'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Make ImageMagik permissive
      shell: bash
      run: sudo sed -i 's/rights=".*"/rights="all"/' /etc/ImageMagick-6/policy.xml
    # Checkout the repository
    - name: Checkout
      uses: danysk/action-checkout@0.2.1
    - name: Prepare the differential documents
      uses: DanySK/auto-latexdiff@64.1.1
      id: latexdiff
      if: inputs.diff-enable == 'true'
      with:
        files: ${{ inputs.diff-files }}
        include-lightweight-tags: ${{ inputs.diff-lightweight-tags }}
        tags: ${{ inputs.diff-tag-regex }}
    - name: Compile LaTeX
      uses: DanySK/compile-latex-action@0.3.87
    - name: Autotag
      uses: DanySK/semver-autotag-action@0.1.0
    - name: Deploy
      if: inputs.publish-enable == 'true'
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        if [[ -z $GITHUB_TOKEN ]]; then
          echo "No token set, cannot deploy"
          false
        else
          if [[ $GITHUB_REF == 'refs/heads/master'
              || $GITHUB_REF == 'refs/heads/main'
              || $GITHUB_REF == 'refs/heads/default'
              || $GITHUB_REF == "refs/tags"*
          ]]; then
            TAG=$(git describe --tags --exact-match HEAD)
            hub release create -m "$(git tag -l --format='%(contents)' "$TAG")" "$TAG" || true
            while IFS= read -r file; do
              pdf="${file%.*}.pdf"
              echo "Delivering file $pdf"
              gh release upload "$TAG" "$pdf" --clobber
            done <<< "$LATEX_SUCCESSES"
          else
            echo "Not running deployment from unknown source: $GITHUB_REF"
          fi
        fi
