name: 'Compile and publish all LaTeX'
description: 'Checkout, compile LaTeX, compute a version, and deploy on GitHub in one shot.'
inputs:
  token:  # github token
    description: 'Github token for deployment.'
    required: true
  publish-enable:
    description: 'Whether the results should be deployed on GitHub. Defaults to true.'
    required: false
    default: true

runs:
  using: "composite"
  steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-cached-tools: 'true'
          remove-codeql: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
    - name: Make ImageMagik permissive
      shell: bash
      run: sudo sed -i 's/rights=".*"/rights="all"/' /etc/ImageMagick-6/policy.xml
    # Checkout the repository
    - name: Checkout
      uses: danysk/action-checkout@0.2.25
    - name: Compile LaTeX
      uses: DanySK/compile-latex-action@2.1.3
    - name: Autotag
      uses: DanySK/semver-autotag-action@0.1.0
    - name: Deploy
      if: inputs.publish-enable == 'true'
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        if [[ -z $GITHUB_TOKEN ]]; then
          echo "No token set, cannot deploy"
          false
        else
          if [[ $GITHUB_REF == 'refs/heads/master'
              || $GITHUB_REF == 'refs/heads/main'
              || $GITHUB_REF == 'refs/heads/default'
              || $GITHUB_REF == "refs/tags"*
          ]]; then
            TAG=$(git describe --tags --exact-match HEAD)
            echo "Preparing release $TAG"
            git tag --delete "$TAG"
            git tag "$TAG"
            git push --tags && echo "Tag $TAG successfully pushed" || true
            gh release create --notes-from-tag "$TAG" || true
            while IFS= read -r file; do
              pdf="${file%.*}.pdf"
              echo "Delivering file $pdf"
              gh release upload "$TAG" "$pdf" --clobber
            done <<< "$LATEX_SUCCESSES"
          else
            echo "Not running deployment from unknown source: $GITHUB_REF"
          fi
        fi
