name: Test and create a release
on:
  push:
    branches-ignore:
      - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:
  workflow_dispatch:

jobs:
  release:
    if: github.event_name == 'push' && contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version-file: package.json
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npx semantic-release
